###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
hop_size: 200            # Hop size.
format: "npy"

###########################################################
#              NETWORK ARCHITECTURE SETTING               #
###########################################################
model_type: "unetts_duration"

unetts_duration_params:
    dataset: multispk_voiceclone

    encoder_hidden_size: 128
    encoder_num_hidden_layers: 2
    encoder_num_attention_heads: 2
    encoder_attention_head_size: 64

    encoder_intermediate_size: 512
    encoder_intermediate_kernel_size: 3
    encoder_hidden_act: "mish"

    hidden_dropout_prob: 0.2
    attention_probs_dropout_prob: 0.1

    num_duration_conv_layers: 2
    duration_predictor_filters: 128
    duration_predictor_kernel_sizes: 3
    duration_predictor_dropout_probs: 0.1

    initializer_range: 0.02
    output_attentions: False
    output_hidden_states: False

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 32              # Batch size.
allow_cache: true           # Whether to allow cache in dataset. If true, it requires cpu memory.
is_shuffle: true            # shuffle dataset after each epoch.

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################
optimizer_params:
    initial_learning_rate: 0.001
    end_learning_rate: 0.00001
    decay_steps: 75000          # < train_max_steps is recommend.
    warmup_proportion: 0.02
    weight_decay: 0.001

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 100000               # Number of training steps.
save_interval_steps: 10000             # Interval steps to save checkpoint.
eval_interval_steps: 1000              # Interval steps to evaluate the network.
log_interval_steps: 500               # Interval steps to record the training log.

###########################################################
#                     OTHER SETTING                       #
###########################################################
num_save_intermediate_results: 1  # Number of batch to be saved as intermediate results.
